"""empty message

Revision ID: 44e1025b1bc7
Revises: e0fe92848a0d
Create Date: 2022-02-07 20:27:54.834869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44e1025b1bc7'
down_revision = 'e0fe92848a0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email_address', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'email_address')
    # ### end Alembic commands ###
