"""empty message

Revision ID: 5bc9098b65ad
Revises: 021f9450f320
Create Date: 2022-03-24 19:26:33.464632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bc9098b65ad'
down_revision = '021f9450f320'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_order_read_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_order_read_time')
    # ### end Alembic commands ###
