"""empty message

Revision ID: ba1559d928b3
Revises: 11c3165f51db
Create Date: 2022-05-04 19:36:18.621619

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ba1559d928b3'
down_revision = '11c3165f51db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_order_read_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_order_read_time', mysql.DATETIME(), nullable=True))
    # ### end Alembic commands ###
